import 'package:mechmate_app/features/owner/owner.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:mechmate_app/core/theme/theme.dart';
import 'package:mechmate_app/shared/shared.dart';

class CreateBookingScreen extends StatefulWidget {
  final ShopModel shop;
  final VehicleApiService? vehicleApiService;
  final BookingApiService? bookingApiService;

  const CreateBookingScreen({
    super.key,
    required this.shop,
    this.vehicleApiService,
    this.bookingApiService,
  });

  @override
  State<CreateBookingScreen> createState() => _CreateBookingScreenState();
}

class _CreateBookingScreenState extends State<CreateBookingScreen> {
  late final VehicleApiService _vehicleApi;
  late final BookingApiService _bookingApi;

  List<VehicleModel> _vehicles = [];
  bool _isLoadingVehicles = true;
  String? _error;

  VehicleModel? _selectedVehicle;
  String? _selectedService;
  DateTime? _selectedDate;
  TimeOfDay? _selectedTime;
  
  bool _isSubmitting = false;

  @override
  void initState() {
    super.initState();
    _vehicleApi = widget.vehicleApiService ?? VehicleApiService();
    _bookingApi = widget.bookingApiService ?? BookingApiService();
    _loadVehicles();
  }

  Future<void> _loadVehicles() async {
    if (!ConnectivityService.instance.isOnline) {
      if (!mounted) return;
      setState(() {
        _error = 'No internet connection. Please check your network.';
        _isLoadingVehicles = false;
      });
      return;
    }

    try {
      final v = await _vehicleApi.getVehicles();
      if (!mounted) return;
      setState(() {
        _vehicles = v;
        _isLoadingVehicles = false;
        if (v.isNotEmpty) {
          _selectedVehicle = v.first;
        }
      });
    } catch (e) {
      debugPrint('CreateBooking: load vehicles failed: $e');
      if (!mounted) return;
      setState(() {
        _error = 'Failed to load vehicles';
        _isLoadingVehicles = false;
      });
    }
  }

  Future<void> _pickDate() async {
    final now = DateTime.now();
    final d = await showDatePicker(
      context: context,
      initialDate: now,
      firstDate: now,
      lastDate: now.add(const Duration(days: 30)),
    );
    if (d != null && mounted) {
      setState(() => _selectedDate = d);
    }
  }

  Future<void> _pickTime() async {
    final t = await showTimePicker(
      context: context,
      initialTime: TimeOfDay.now(),
    );
    if (t != null && mounted) {
      setState(() => _selectedTime = t);
    }
  }

  Future<void> _submitBooking() async {
    if (_selectedVehicle == null || _selectedService == null || _selectedDate == null || _selectedTime == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please fill all fields')),
      );
      return;
    }

    setState(() => _isSubmitting = true);

    try {
      final dt = DateTime(
        _selectedDate!.year,
        _selectedDate!.month,
        _selectedDate!.day,
        _selectedTime!.hour,
        _selectedTime!.minute,
      );

      final booking = BookingModel(
        id: '', // Generated by backend
        ownerId: '', // Set by backend based on token
        workshopId: widget.shop.id,
        workshopName: widget.shop.name,
        service: _selectedService!,
        vehicleType: _selectedVehicle!.type,
        vehicleNumber: _selectedVehicle!.number,
        vehicleMake: _selectedVehicle!.make,
        vehicleModel: _selectedVehicle!.model,
        status: 'pending',
        scheduledAt: dt,
        createdAt: DateTime.now(),
      );

      await _bookingApi.createBooking(booking);

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Booking created successfully!'), backgroundColor: AppColors.success),
      );
      Navigator.pop(context); // close create booking
      Navigator.pop(context); // close details sheet if needed, but since it's a push we just pop once to return to map
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error: $e'), backgroundColor: AppColors.error),
      );
    } finally {
      if (mounted) setState(() => _isSubmitting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      backgroundColor: isDark ? AppColors.darkBg : AppColors.lightBg,
      appBar: AppBar(
        title: const Text('Book Service'),
        backgroundColor: isDark ? AppColors.darkBg : AppColors.lightBg,
        elevation: 0,
      ),
      body: _isLoadingVehicles
          ? const Center(child: CircularProgressIndicator())
          : _error != null
              ? ErrorRetry(message: _error!, onRetry: () {
                  setState(() {
                    _error = null;
                    _isLoadingVehicles = true;
                  });
                  _loadVehicles();
                })
              : SingleChildScrollView(
                  padding: const EdgeInsets.all(20),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(widget.shop.name, style: const TextStyle(fontSize: 22, fontWeight: FontWeight.bold)),
                      const SizedBox(height: 20),
                      
                      const Text('Select Service', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                      const SizedBox(height: 10),
                      Wrap(
                        spacing: 8,
                        children: widget.shop.services.map((s) {
                          final selected = _selectedService == s;
                          return ChoiceChip(
                            label: Text(s),
                            selected: selected,
                            onSelected: (val) => setState(() => _selectedService = val ? s : null),
                            selectedColor: AppColors.primaryOrange.withValues(alpha: 0.2),
                            labelStyle: TextStyle(color: selected ? AppColors.primaryOrange : (isDark ? Colors.white : Colors.black)),
                          );
                        }).toList(),
                      ),
                      const SizedBox(height: 24),

                      const Text('Select Vehicle', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                      const SizedBox(height: 10),
                      if (_vehicles.isEmpty)
                        const Text('No vehicles added. Please add one from My Vehicles.')
                      else
                        DropdownButtonFormField<VehicleModel>(
                          initialValue: _selectedVehicle,
                          isExpanded: true,
                          decoration: InputDecoration(
                            border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                            filled: true,
                            fillColor: isDark ? AppColors.darkCard : AppColors.lightCard,
                          ),
                          items: _vehicles.map((v) => DropdownMenuItem(
                            value: v,
                            child: Text('${v.make} ${v.model} (${v.number})'),
                          )).toList(),
                          onChanged: (val) => setState(() => _selectedVehicle = val),
                        ),
                      const SizedBox(height: 24),

                      const Text('Schedule', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                      const SizedBox(height: 10),
                      Row(
                        children: [
                          Expanded(
                            child: OutlinedButton.icon(
                              onPressed: _pickDate,
                              icon: const Icon(Icons.calendar_today_rounded),
                              label: Text(_selectedDate == null ? 'Select Date' : DateFormat('MMM dd, yyyy').format(_selectedDate!)),
                            ),
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: OutlinedButton.icon(
                              onPressed: _pickTime,
                              icon: const Icon(Icons.access_time_rounded),
                              label: Text(_selectedTime == null ? 'Select Time' : _selectedTime!.format(context)),
                            ),
                          ),
                        ],
                      ),
                      
                      const SizedBox(height: 40),
                      SizedBox(
                        width: double.infinity,
                        height: 54,
                        child: PrimaryButton(
                          label: 'Confirm Booking',
                          isLoading: _isSubmitting,
                          onPressed: _submitBooking,
                        ),
                      ),
                    ],
                  ),
                ),
    );
  }
}
